name: Drake Merge Conflicts

on:
  pull_request_target:
    branches:
      - 1.21-latin
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    if: github.repository == 'SlimefunNewHorizons/drakes-slimefun-labs'
    name: Check for merge conflicts
    runs-on: ubuntu-latest

    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: '⚡ Merge Conflicts'
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
